Eugenetanwl3881/MaybeStocks

- src/App.js
> Eugene's changes

- src/components/utils/stockAPI.js
Started on using API to fetch stock data
> Fetch Stock Data

- src/Pages/MainPage.js
Displays the google account name that the user used to log in with
> Added a welcome message

- package-lock.json
- package.json
- src/Pages/MainPage.js
- src/Pages/PortfolioPage.js
- src/components/DataFetch.js
- src/hooks/useFetch.js
Added useFetch hook to fetch data from API easier
> Added useFetch hook to fetch data from API easier

- src/Pages/PortfolioPage.js
- src/components/TransactionTable/TransactionTable.js
Removed "hardcoding"of company name and price for earlier test
> Improved table by allowing information to be dynamic

- src/Pages/BuyPage.js
- src/Pages/PortfolioPage.js
- src/Pages/SellPage.js
- src/components/BuyInput/BuyInput.js
- src/components/SellInput/SellInput.js
- src/components/TransactionTable/TransactionTable.js
- src/hooks/useFetch.js
Users can only buy on the buy page and sell on the sell page. To see their buying/selling, users can go to their portfolio page.
> Shifted the input box to the buy and sell page.

- src/Pages/BuyPage.js
- src/Pages/MainPage.js
- src/Pages/PortfolioPage.js
- src/Pages/SellPage.js
Added functionality to search for stocks
> Searching For Stocks in Buy/Sell Page

- src/Pages/BuyPage.js
- src/Pages/SellPage.js
Added placeholder values for the stock input search
> placeholder values for search added

- src/Pages/BuyPage.js
- src/Pages/PortfolioPage.js
- src/Pages/SellPage.js
- src/components/BuyInput/BuyInput.js
- src/components/SellInput/SellInput.js
Using useRef hooks for searching and updating Input Validation
> Using useRef hooks for searching and updating Input Validation

- src/Pages/BuyPage.js
- src/Pages/SellPage.js
Updated Search Button UI using Material UI
> Updated Search Button UI using Material UI

- src/Pages/BuyPage.js
- src/Pages/PortfolioPage.js
- src/components/BuyInput/BuyInput.js
> Got Basic Portfolio Page Working

- src/components/ResponsiveAppBar/ResponsiveAppBar.js
- src/components/SellInput/SellInput.js
- src/components/TransactionTable/TransactionTable.js
Transaction table will only be updated if portfolio table is updated. Also, fixed the bugs shown in the console on the web application.
> Changed how transaction table is updated

- src/App.js
- src/Pages/LoginOrSignUpPage.js
- src/Pages/LoginPage.js
- src/Pages/SignUpPage.js
- src/components/SignUp/SignUp.js
Users will either see the login page or the signup page
> Added a LoginOrSignUpPage

- src/Pages/BuyPage.js
- src/Pages/HomePage.js
- src/components/BuyInput/BuyInput.js
- src/components/ResponsiveAppBar/ResponsiveAppBar.js
Users can now see the amount of money they have on the Home Page
> Added a wallet representation on the Home Page

- src/Pages/BuyPage.js
- src/Pages/HomePage.js
- src/Pages/SellPage.js
- src/components/BuyInput/BuyInput.js
- src/components/WatchlistTable/WatchlistTable.js
Everything is working. Adding of stocks, refreshing prices and percentage changes. Deleting of stocks.
> Added watchlist functionalities.

- src/Pages/ForumPage.js
- src/Pages/LoginOrSignUpPage.js
- src/Pages/MainPage.js
- src/components/ResponsiveAppBar/ResponsiveAppBar.js
Added some skeletal code to forum page as well
> Fixed navigation between sign in and sign up.

- src/components/BuyInput/BuyInput.js
- src/components/Popup/Popup.css
- src/components/Popup/Popup.js
- src/components/SellInput/SellInput.js
Got popup boxes working for both buy and sell pages. Try it
> PopUp boxes for buy and sell

- src/Pages/ForumPage.js
> Updated input field

- src/App.js
- src/components/Popup/Popup.js
- src/components/Popup/Popup.test.js
Added Jest and React Testing for PopUp. We will add more
> Added Jest and React Testing

- src/Pages/ForumPage.js
- src/components/Popup/Popup.test.js
Updated Input field for forum and added new test for Pop Up
> Updated Input field for forum and added new test

- package-lock.json
- package.json
- src/components/BuyInput/BuyInput.js
- src/components/BuyInput/BuyInput.test.js
- src/components/SellInput/SellInput.js
Updated PopUp error messages, added more tests for buy input
> Updated PopUp error messages, added more tests

- src/Pages/ForumPage.js
- src/Pages/HomePage.js
- src/Pages/MainPage.js
- src/Pages/PortfolioPage.js
Updated Portfolio to include wallet + UI updates to the forum page and titles
> Updated Portfolio to include wallet + UI updates

- src/Pages/LoginPage.js
- src/components/SignIn/SignIn.js
- src/components/SignUp/SignUp.js
Enhanced the UI of our login and sign up pages due to user comments
> Touched up on Login and Sign up UI

- src/Pages/BuyPage.js
- src/Pages/PortfolioPage.js
- src/Pages/SellPage.js
- src/components/BuyInput/BuyInput.js
- src/components/PortfolioTable/PortfolioTable.js
- src/components/ResponsiveAppBar/ResponsiveAppBar.js
- src/components/SellInput/SellInput.js
- src/components/TransactionTable/TransactionTable.js
Added Refresh functionality for portfolio. Added external links. Updated responsive app bar
> Portfoliochanges
